### ISSUE TITLE
Draw The Mock-ups

### ISSUE THREAD

**Issue by oralemre** [bounswe/bounswe2015group6#109]
Draw the mock-ups that we talked about that at today's meeting.

**Comment by berkdilek** [comment]
Mockups are drawn and showed to Alp Kındıroğlu. After his feedbacks I redraw 'Homepage', 'Graph View', 'Topic View' mockups. Suzan Üsküdarlı and Alp Kındıroğlu evaluated these mockups and made comments, in general these mockups are enough for validation at this level. But ,of course, after final UI design we are going to meet and ask feedback to validate our work.

**Comment by berkdilek** [comment]
![Uploading GraphView.jpg…]()
![Uploading Homepage.jpg…]()
![Uploading TopicView.jpg…]()

**Comment by berkdilek** [comment]
There three mockups can be seen here:

![graphview](https://cloud.githubusercontent.com/assets/12131227/10769634/a460a5a2-7cef-11e5-896a-9cfc8a681818.jpg)
![homepage](https://cloud.githubusercontent.com/assets/12131227/10769595/80dc0a40-7cef-11e5-9716-11e99a25fef7.jpg)
![topicview](https://cloud.githubusercontent.com/assets/12131227/10769596/80e1f040-7cef-11e5-9068-a0e6fc5a79a6.jpg)
