### ISSUE TITLE
Modify Project Plan

### ISSUE THREAD

**Issue by hbaristr** [bounswe/bounswe2015group6#121]
Assign some Back-End works to Barış Özmen and remove his works in Web.

**Comment by hbaristr** [comment]
I have assigned myself to some Back-End jobs until 2. milestone. Please tell me if anyone also wants these jobs.

I didn't remove myself from Web jobs, because I didn't know whom to assign them.

**Comment by EvrenCivelek** [comment]
I think the activity on github is more important than that and also some project plan has been modified so I will close the issue
