### ISSUE TITLE
Saving logged in user's info in device

### ISSUE THREAD

**Issue by berkdilek** [bounswe/bounswe2015group6#143]
After a user logs in, this user's info should be stored in device. Following links can be used as reference:
http://stackoverflow.com/questions/10209814/saving-user-information-in-app-settings

http://loopj.com/android-async-http/

**Comment by oralemre** [comment]
I wrote following code to SignInActivity


                        SharedPreferences settings = getSharedPreferences("UserInfo", 0);
                        SharedPreferences.Editor editor = settings.edit();
                        editor.putString("Username",response.getString("username"));
                        editor.putString("ID", Integer.toString(response.getInt("id")));
                        editor.commit();

                        Intent intent = new Intent(context,HomePageActivity.class);
                        startActivity(intent);
                        

And I created HomePageActivity.java to show saved info of logged in user (his/her username and id)




    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_home_page);
        TextView txtWel = (TextView) findViewById(R.id.txtWelcome);
        SharedPreferences settings = getSharedPreferences("UserInfo", 0);
        txtWel.setText("WELCOME UserName: " + settings.getString("Username", "").toString() +
        " ID: " + settings.getString("ID", "").toString());

    }

**Comment by oralemre** [comment]
I committed and pushed it to Android_dev branch.
