### ISSUE TITLE
Decide and implement how tags should be given to a topic.

### ISSUE THREAD

**Issue by berkdilek** [bounswe/bounswe2015group6#153]

**Comment by berkdilek** [comment]
Sami selam,

Topic Create sayfasini ben yaptigimdan bu taski aciklayayim sana biraz: 
Tag yapisi henuz tam belli olmadigindan butun Topicler null bir TagArrayi ile olusuyor. Topic Create ekranina bakarsan orada bir Tags diye EditText var. Teoride kullanicinin buraya tagleri gimesi lazim. Bizin de girdigi tagleri bir arraye doldurup yollamamiz gerek. Buradaki sorun kullanici nasil bir formatta taglari verecek. Aklima gelen birkac ihtimal:
1- Tagleri bosluk birakmadan virgul ile ayirarak verir. Biz de butun stringi virgullerden split ederek arrayi olustururuz.( murder,gun,police -> Tags = [murder, gun, police];) gibi.
2 - # kullanarak isaretten sonra gelen ve oteki isarete kadar olan kismi tag olarak aliriz. (#pistol gun#murder#police -> Tags = [pistol gun, murder, police]) gibi.
3 - Hergirdigi Tagden sonra ekle tarzi bir butonla tagi ekletiriz ve textediti sileriz sonra tekrar girdiririz. Bir yandan da arrayi dolduruz her onclick'te

Burada baska ihtimaller de var. UX acisindan dusunup karari sen ver. 3. secenek UX acisindan zayif duruyor onu secersen de biraz degisitirip yaparsin.

En onemlisi Back-end'den Andac ile konusup onun kafasindaki tag formatina kolayca modifiye edilcek sekilde implement etmeye calisalim, cunku semantic tage gecebilrisek degisiklik gerektirecek bir task bu.

Hadi kolay gelsin, opuyorum gozlerinden.

**Comment by mahmutsami106** [comment]
Tags are added to the topic by seperating each of them by space.
