### ISSUE TITLE
Relation create screen implentation. [Android]

### ISSUE THREAD

**Issue by berkdilek** [bounswe/bounswe2015group6#154]
This is the screen where user create a relation between two topics. This screen should have two EditTexts and a Button. EditTexts should take the title of the topics and onclick event of button should create this task like Create Topic Activity. Backend services are ready. 

Also logged in user can reach this page via nav_bar item.

Another point is if we decide that edges have relation type (result, cause etc) another EditText is necessary.

**Comment by oralemre** [comment]
I done it and also tested it. It is ready for deployment
