### ISSUE TITLE
Correct assigning self relation problem

### ISSUE THREAD

**Issue by temelkandaz** [bounswe/bounswe2015group6#167]
A topic can be connected to itself please correct this bug.
![screen shot 2015-12-12 at 23 16 00](https://cloud.githubusercontent.com/assets/12714838/11763930/890b5846-a126-11e5-98d9-c8c3468c7b53.png)

**Comment by temelkandaz** [comment]
Any update on this?

**Comment by karacakir** [comment]
It asks before creating connection to make user sure.
