### ISSUE TITLE
Get Something Went Wrong message when creating a new topic

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2015group6#206]
I logged in as "uskudarli" (existing account).

Created a couple of topics, but I am confused. I keep getting "Something Went Wrong' message when creating a new topic.

First I created Net Neutrality topic. Then I created posts and tags. I have a post about Mark Zuckerberg. 

I wanted to create a topic Mark Zuckerberg, however it says the topic already exists. Then I went trying to create topics to see what is happening and I kept getting Something Went Wrong or Topic Already Exists. 

Something went wrong is better than a 500 error-- granted. But, no idea what is going on.

![topic creation issues](https://cloud.githubusercontent.com/assets/1347035/12122766/c12ebdc2-b3e5-11e5-85dd-631574ecb23f.png)

I expected to be able to created a topic called Mark Zuckerberg. If that became a topic from my tags, I am confused.

**Comment by andactan** [comment]
Hello there,

We doubt that error is a consequence of search API faulty we are using. We are working on the issue currently.

Regards.

**Comment by temelkandaz** [comment]
Thanks for reporting the bug. 

We were already aware of something was causing our system to malfunction but haven't exactly find the problem yet. I am helping Andac to fix this bug however I couldn't assign us both in the issue.

**Comment by temelkandaz** [comment]
I tried to follow your steps.

- I created a topic called 'Net Neutrality' with tags 'Suzan Test' and 'Mark Zuckerberg'.
![screen shot 2016-01-06 at 22 50 08](https://cloud.githubusercontent.com/assets/12714838/12154847/9950b5c2-b4ca-11e5-80e9-6e8afc187d60.png)

- No topic named 'Mark Zuckerberg' is created after first step. Then I added a tag 'Facebook Founder' to 'Net Neutrality' from topic page and again no creation of a new topic is observed.
![screen shot 2016-01-06 at 22 50 34](https://cloud.githubusercontent.com/assets/12714838/12154857/a5b7fc3a-b4ca-11e5-9922-7cf6e91c0b75.png)

- I added a topic Mark Zuckerberg.
![screen shot 2016-01-06 at 22 51 37](https://cloud.githubusercontent.com/assets/12714838/12154893/ef061c28-b4ca-11e5-8403-ba31eff63a47.png)

- I created a relation between Mark Zuckerberg and Net Neutrality. Both of the topics are accepted from the system and the relation is created.
![screen shot 2016-01-06 at 22 52 02](https://cloud.githubusercontent.com/assets/12714838/12154926/17702460-b4cb-11e5-8bf5-280b2282fafc.png)

- Final View
![screen shot 2016-01-06 at 22 52 38](https://cloud.githubusercontent.com/assets/12714838/12154933/205c39ce-b4cb-11e5-8099-7ccdb8b8c843.png)

**Comment by temelkandaz** [comment]
Please see my comment on the issue and close it if we eliminated your concerns.

**Comment by andactan** [comment]
Hi there again,

It has been a while since we commented on the issue, but now everthing runs smootly as expected.

Bugs are now defected and system runs functionally.

Cheers.
