### ISSUE TITLE
Search is not working, no results are returned

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2015group6#213]
Regardless of what I search for, there are no results.

I tried

Pakistan
Serial
Adnan Syed
...

0 topics and 0 users

**Comment by andactan** [comment]
It was a purely search API malfunctioning which is to say that there are times API does not allow some specific characters to include in its configuration files. (Actually, there are some restrictions not to use blanks, question marks in configuration file). It now fulfills its breath of life.

We also noticed that there are couple of issues about prioritizing the search results which one comes first and which one comes later. We also working on the problem.

Have a nice day.

**Comment by temelkandaz** [comment]
Shall we close this issue, if your concerns are satisfied?

**Comment by uskudarli** [comment]
I did not understand your explanation, but checked and it is working now.

With the complex graph, without search life would not be cool.

Thanks. Closing it.

**Comment by uskudarli** [comment]
i closed it after checking it out.

thanks!
